[package]
edition = "2021"
name = "advent-of-code-2023"
version = "0.1.0"

[lib]
bench = false

[dependencies]
anyhow = "1.0.89"
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
num-integer = "0.1.46"
rayon = "1.10.0"
regex = "1.11.0"


[features]
full_input = []
